### ISSUE TITLE
incompatibilite avec slurm 22.05

### ISSUE THREAD

**Issue by bellencoATatos** [cea-hpc/bridge#2]
Jusqu'ici, l'outil fonctionnait bien, nous étions en version slurm-17.11. Suite à la mise à jour en slurm-22.05, impossible de réinstaller l'outil. Il n'a pas l'air compatible avec cette version. Une mise à jour est-elle prévue ?

en vous remerciant

**Comment by od-cea** [comment]
Bonjour,
Nous venons de faire une mise à jour du dépôt. Cette dernière contient l'ensemble de nos modifications à ce jour. Nous n'avons fait aucun test avec la version 22 de slurm, aussi, dites moi si ça marche avec.
La mise à jour a nécessité la réécriture de l'historique - j'en suis particulièrement désolé : vous serez probablement obligé de cloner le repository à nouveau.

**Comment by bellencoATatos** [comment]
Bonjour, 
nous venons de compiler et d'installer. nos premiers tests cote admins sont ok avec 22.05.
Si nous venions à avoir des retours négatifs de nos utilisateurs, nous vous en feront part. merci
beaucoup.
